<?php

// Rol bazlı yetki tanımlamaları
// true = erişim var, yoksa erişim yok

return [
    'admin' => [
        'dashboard' => true,
        'personel_islemleri' => true,
        'personel_kartlari' => true,
        'cihaz_islemleri' => true,
        'cihaz_transfer' => true,
        'raporlar' => true,
        'ek_kazanclar' => true,
        'avans_kesintiler' => true,
        'toplu_islemler' => true,
        'toplu_maas' => true,
        'toplu_hareket' => true,
        'toplu_izin' => true,
        'toplu_avans' => true,
        'toplu_prim' => true,
        'toplu_yemek' => true,
        'toplu_servis_yol' => true,
        'toplu_giris_cikis' => true,
        'toplu_mesaj' => true,
        'toplu_mail' => true,
        'zamanlanmis_bildirimler' => true,
        'tanim_islemleri' => true,
        'kullanici_yonetimi' => true,
        'mail_ayarlari' => true,
        'mesaj_ayarlari' => true,
        'subeler' => true,
        'servisler' => true,
    ],

    'kullanici' => [
        'dashboard' => true,
        'personel_islemleri' => true,
        'personel_kartlari' => true,
        'cihaz_islemleri' => true,
        'cihaz_transfer' => true,
        'raporlar' => true,
        'ek_kazanclar' => false,
        'avans_kesintiler' => false,
        'toplu_islemler' => false,
        'tanim_islemleri' => false,
        'kullanici_yonetimi' => false,
        'mail_ayarlari' => false,
        'mesaj_ayarlari' => false,
        'subeler' => false,
        'servisler' => false,
    ],

    'muhasebe' => [
        'dashboard' => true,
        'personel_islemleri' => true,
        'personel_kartlari' => true,
        'cihaz_islemleri' => false,
        'cihaz_transfer' => false,
        'raporlar' => true,
        'ek_kazanclar' => true,
        'avans_kesintiler' => true,
        'toplu_islemler' => true,
        'toplu_maas' => true,
        'toplu_hareket' => false,
        'toplu_izin' => false,
        'toplu_avans' => true,
        'toplu_prim' => true,
        'toplu_yemek' => true,
        'toplu_servis_yol' => true,
        'toplu_giris_cikis' => false,
        'toplu_mesaj' => false,
        'toplu_mail' => false,
        'zamanlanmis_bildirimler' => false,
        'tanim_islemleri' => false,
        'kullanici_yonetimi' => false,
        'mail_ayarlari' => false,
        'mesaj_ayarlari' => false,
        'subeler' => false,
        'servisler' => false,
    ],

    'ik' => [
        'dashboard' => true,
        'personel_islemleri' => true,
        'personel_kartlari' => true,
        'cihaz_islemleri' => true,
        'cihaz_transfer' => true,
        'raporlar' => true,
        'ek_kazanclar' => false,
        'avans_kesintiler' => false,
        'toplu_islemler' => true,
        'toplu_maas' => false,
        'toplu_hareket' => true,
        'toplu_izin' => true,
        'toplu_avans' => false,
        'toplu_prim' => false,
        'toplu_yemek' => false,
        'toplu_servis_yol' => false,
        'toplu_giris_cikis' => true,
        'toplu_mesaj' => true,
        'toplu_mail' => true,
        'zamanlanmis_bildirimler' => true,
        'tanim_islemleri' => false,
        'kullanici_yonetimi' => false,
        'mail_ayarlari' => false,
        'mesaj_ayarlari' => false,
        'subeler' => false,
        'servisler' => false,
    ],

    'izleyici' => [
        'dashboard' => true,
        'personel_islemleri' => true,
        'personel_kartlari' => false,  // sadece liste, düzenleme yok
        'cihaz_islemleri' => false,
        'cihaz_transfer' => false,
        'raporlar' => true,
        'ek_kazanclar' => false,
        'avans_kesintiler' => false,
        'toplu_islemler' => false,
        'tanim_islemleri' => false,
        'kullanici_yonetimi' => false,
        'mail_ayarlari' => false,
        'mesaj_ayarlari' => false,
        'subeler' => false,
        'servisler' => false,
    ],
];
